"""PR description and report generation."""

from dataclasses import dataclass
from typing import List

from fixforward.detector import Ecosystem
from fixforward.classifier import ClassifiedFailure
from fixforward.copilot import PatchResult
from fixforward.verifier import VerifyResult


@dataclass
class PRReport:
    title: str
    body: str


def generate_report(
    classifications: List[ClassifiedFailure],
    patch: PatchResult,
    verify_result: VerifyResult,
    ecosystem: Ecosystem,
) -> PRReport:
    """Generate PR title and body."""
    # Build title
    categories = sorted(set(c.category.value for c in classifications))
    if len(categories) == 1:
        title = f"fix: auto-resolve {categories[0]} failure"
    elif len(categories) <= 3:
        title = f"fix: auto-resolve {', '.join(categories)} failures"
    else:
        title = f"fix: auto-resolve {len(classifications)} test failures"

    if len(title) > 72:
        title = f"fix: auto-resolve {len(classifications)} test failures"

    # Build body
    body = _build_body(classifications, patch, verify_result, ecosystem)

    return PRReport(title=title, body=body)


def _build_body(
    classifications: List[ClassifiedFailure],
    patch: PatchResult,
    verify_result: VerifyResult,
    ecosystem: Ecosystem,
) -> str:
    """Build the PR body in Markdown."""
    sections = []

    # What happened
    failure_list = "\n".join(
        f"- **{c.failure.test_name}** ({c.category.value}): {c.summary}"
        for c in classifications
    )
    sections.append(
        f"## What happened\n\n"
        f"{ecosystem.value.capitalize()} tests were failing with "
        f"{len(classifications)} error(s):\n\n"
        f"{failure_list}"
    )

    # Root cause
    if patch.explanation:
        sections.append(
            f"## Root cause\n\n{patch.explanation}"
        )

    # What changed
    files_list = "\n".join(
        f"- `{change.file_path}`"
        for change in patch.changes
    )
    sections.append(
        f"## What changed\n\n{files_list}"
    )

    # Verification
    orig = verify_result.original
    after = verify_result.after_fix
    status = "All passing" if verify_result.all_passing else f"{after.failed_count} still failing"
    conf_pct = f"{verify_result.confidence:.0%}"

    sections.append(
        f"## Verification\n\n"
        f"| Metric | Before | After |\n"
        f"|--------|--------|-------|\n"
        f"| Failed | {orig.failed_count} | {after.failed_count} |\n"
        f"| Passed | {orig.passed_count} | {after.passed_count} |\n"
        f"| Total  | {orig.total_tests} | {after.total_tests} |\n"
        f"| Status | Failing | {status} |\n\n"
        f"**Confidence score:** {conf_pct}"
    )

    # Footer
    sections.append(
        "---\n\n"
        "Generated by [FixForward](https://github.com/stackmasteraliza/fixforward) "
        "powered by GitHub Copilot CLI"
    )

    return "\n\n".join(sections)
